### ISSUE TITLE
If user insert a wrong password the system will be frozen

### ISSUE THREAD

**Issue by PeopleInside** [ReFlar/twofactor#11]
This extension seems to be not compatible with the last Flarum version, I have to unistall it.
If the user put a wrong password the login button once pressed will be frozen.

Flarum 10 beta.

**Comment by KyrneDev** [comment]
Fixed in 622af20fdf804943d1c4d87afe00854d63c633a8

**Comment by PeopleInside** [comment]
Cannot test now but will close the issue for the moment. Thanks
